baseURL = "https://byteworx.be"
title = "Byteworx | Byteworx IT consultancy - Connecting professionals"
languageCode = "nl-BE"
defaultContentLanguage = "be"
paginate = "7"

[params]
fancyTitle = "Byteworx" # title for frontpage, may include image
copyright = "Byteworx.be"
description2 = "Byteworx is een next-level IT-consultancy organisatie die zich inzet om klanten te verbinden met kwalitatieve, gepassioneerde softwareontwikkelaars. Onze missie bestaat er uit om klanten en werknemers tevredenheid te maximaliseren."
description = 'Next level Java en iOS IT consultancy.'
startbuttonText = "Over ons"
startbuttonLink = "#over-ons"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '#over-ons'
title = "Over ons"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Haal het beste uit jezelf.<br />'
body = '''
 Bij Byteworx geloven we in jouw talenten. Daarom staat het uitbreiden en bijschaven van jouw skills bij ons centraal.<br/>
 We doen dit door een individueel ontwikkeltraject uit te stippelen met als doel je te laten uitgroeien tot een ontwikkelaar waar andere op kunnen rekenen.
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic02.webp"
title = 'Ontwikkel je skills.'
body = 'Onder het motto een dag niet geleerd is een dag niet geleefd, organiseren we regelmatig een hackathon of workshop rond een bepaalde technologie.'

[[params.two.section]]
img = "img/pic01.webp"
title = 'Afterwork activiteiten.'
body = 'We zetten in op het vormen van een hechte groep. Dit doen we door regelmatig een afterwork activiteit te organiseren, <br/>denk aan een barbecue, karting event, uitstap, ...'

[[params.two.section]]
img = "img/pic03.webp"
title = 'De beste voorwaarden.'
body = 'Dankzij onze vlakke structuur en lage overhead kunnen we de beste condities aanbieden in de markt.<br/> We geloven in eerlijke verloning voor eerlijk werk.'

[params.three]
enable = true
title = 'Onze kernwaarden.'
body = '''
Principes om naar te leven.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Zelfontplooiing"
body = "Samen kijken we waar je technische kennis bijgeschaafd kan worden zodat je vol zelfvertrouwen aan je opdracht kan beginnen."

[[params.three.feature]]
icon = "solid fa-handshake"
title = "Persoonlijke aanpak"
body = "Bij ons ben je geen nummer. Een luisterend oor, een technische uitdaging, we staan telkens klaar om je te begeleiden."

[[params.three.feature]]
icon = "fa-heart"
title = "Feel good"
body = "We doen alles voor een ideale work-lifebalance en streven ernaar om een hechte groep professionals te creëren."

[[params.three.feature]]
icon = "solid fa-code"
title = "Loon naar werk"
body = "Transparante, eerlijke verloning op maat is onze standaard aanpak."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Professionalisme"
body = "We helpen je uit te groeien tot een expert professional door te investeren in jouw ontwikkeling."

[[params.three.feature]]
icon = "fa-flag"
title = "Vlakke structuur"
body = "We geloven niet in een top-down structuur en proberen iedereen aanspreekbaar te maken. Heb je een probleem of zit je met iets dan vind je bij ieder van ons een luisterend oor."

[params.cta]
enable = true
title = "Nu is het aan jou."
body = "Ben jij een Java of iOS ontwikkelaar en kan je jezelf vinden in onze kernwaarden en wil je ervaren hoe het is om te werken voor een bedrijf dat jou centraal stelt.<br/> Aarzel dan niet en neem contact op."

[[params.cta.link]]
href = "https://wa.me/32456648266"
text = "Contacteer"
special = true

[[params.cta.link]]
href = "#kernwaarden"
text = "Kernwaarden"
special = false

[params.contact]
enable = true
title = "Contacteer ons"
body = "Laat een bericht na of stuur ons via WhatsApp."
phone = "32456648266"
address = "Ranstsebinnenweg 21<br />2520 Ranst<br /> België"
email = "info@byteworx.be"
subject = "Byteworx website formulier"
formspree_form_id = "xrgvwvwk"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 10
languageName = "English"

[languages.be]
weight = 0
languageName = "Dutch"
